# Generated by Django 5.1.4 on 2024-12-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transferlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log da Transferência', 'verbose_name_plural': 'Logs de Transferências'},
        ),
    ]
